AllCops:
  NewCops: disable

Layout/LineLength:
  Max: 140

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 25

Style/Documentation:
  Enabled: False
