name: Build + publish

on:
  push:
    tags: [ v* ]
jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Release Gem
        if: contains(github.ref, 'refs/tags/v')
        uses: cadwallion/publish-rubygems-action@master
        env:
          RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
          RELEASE_COMMAND: bundle exec rake release
    # steps:
    # - uses: actions/checkout@v3
    # - name: Set up Ruby
    #   uses: ruby/setup-ruby@v1
    #   with:
    #     ruby-version: .ruby-version
    #     bundler-cache: true
